// Copyright (c) 2026 edwest19
// Generated by Claude.

using System.Collections.ObjectModel;
using SecretLead.Models;
using SecretLead.Services;
using Windows.Storage;
using Windows.Storage.Pickers;
using Windows.System;

namespace SecretLead.ViewModels;

/// <summary>One card's worth of display — the Category/Nickname positional roles (README.md §4), plus the underlying record.</summary>
public sealed class RecordSummary
{
    public required EntityRecord Record { get; init; }
    public required string CategoryValue { get; init; }
    public required string NicknameValue { get; init; }
}

/// <summary>One read-only tag/value pair, for the record detail view.</summary>
public sealed class TagValue
{
    public required string TagName { get; init; }
    public required string Value { get; init; }
}

/// <summary>
/// One editable tag/value pair, for the Add and Edit forms. Observable on
/// its own so a TextBox bound to <see cref="Value"/> updates correctly
/// even when Clear resets it from code, not just from user typing.
/// </summary>
public sealed class EditableTagValue : ObservableObject
{
    private string _value = string.Empty;

    public required string TagName { get; init; }

    public string Value
    {
        get => _value;
        set => SetProperty(ref _value, value);
    }
}

/// <summary>Which overlay panel, if any, is currently shown over the record list.</summary>
public enum BrowseOverlay
{
    None,
    Detail,
    EditRecord,
    AddRecord,
}

/// <summary>
/// Backs the browse/list screen. Four sections, per the owner's spec:
/// <list type="number">
/// <item>File nav — switch between entities that already exist in AppData (README.md §6). Export/Print act on the whole selected entity from here, not just the current category.</item>
/// <item>Category nav — step through distinct values of the tag file's first tag (the Category role, README.md §4). The record list only ever shows the currently selected value.</item>
/// <item>Search — filters within that category by the second tag (the Nickname role).</item>
/// <item>Records — cards showing only the first two tags; Add/Edit pop an overlay with as few active buttons as possible, so a stray click can't undo what was just typed.</item>
/// </list>
/// </summary>
public sealed class BrowsePageViewModel : ObservableObject
{
    private readonly EntityStore _entityStore = new();

    private List<EntityRecord> _allRecords = [];
    private TagFileDefinition? _tagFile;
    private EntityRecord? _detailTargetRecord;

    private IReadOnlyList<string> _entityNames = [];
    private string? _selectedEntityName;

    private IReadOnlyList<string> _distinctCategories = [];
    private int _selectedCategoryIndex = -1;

    private string _searchText = string.Empty;

    private BrowseOverlay _overlay = BrowseOverlay.None;
    private string _selectedRecordTitle = string.Empty;
    private IReadOnlyList<TagValue> _detailFields = [];
    private string _validationMessage = string.Empty;

    // ---- 1. File nav ----

    public IReadOnlyList<string> EntityNames
    {
        get => _entityNames;
        private set
        {
            if (SetProperty(ref _entityNames, value))
            {
                OnPropertyChanged(nameof(HasEntities));
            }
        }
    }

    public bool HasEntities => EntityNames.Count > 0;

    public string? SelectedEntityName
    {
        get => _selectedEntityName;
        set
        {
            if (SetProperty(ref _selectedEntityName, value) && value is not null)
            {
                LoadEntity(value);
            }
        }
    }

    /// <summary>Export and Print are both disabled when there's nothing to write.</summary>
    public bool CanExportOrPrint => _allRecords.Count > 0;

    public RelayCommand ExportCommand { get; }
    public RelayCommand PrintCommand { get; }

    // ---- 2. Category nav ----

    public IReadOnlyList<string> DistinctCategories
    {
        get => _distinctCategories;
        private set => SetProperty(ref _distinctCategories, value);
    }

    public int SelectedCategoryIndex
    {
        get => _selectedCategoryIndex;
        private set
        {
            if (SetProperty(ref _selectedCategoryIndex, value))
            {
                OnPropertyChanged(nameof(SelectedCategory));
                OnPropertyChanged(nameof(CategoryPositionText));
                OnPropertyChanged(nameof(CanGoToFirstOrPrevious));
                OnPropertyChanged(nameof(CanGoToNextOrLast));
                ApplyFilter();
            }
        }
    }

    public string? SelectedCategory =>
        _selectedCategoryIndex >= 0 && _selectedCategoryIndex < DistinctCategories.Count
            ? DistinctCategories[_selectedCategoryIndex]
            : null;

    /// <summary>e.g. "Residential · 3 of 12" — the value comes from whatever the tag file calls its first tag, not literally "Category".</summary>
    public string CategoryPositionText => SelectedCategory is { } category
        ? $"{category} · {_selectedCategoryIndex + 1} of {DistinctCategories.Count}"
        : "No records yet";

    /// <summary>The current tag file's first tag name, used as this section's label (README.md §4 — "Category" is only this demo's name for it).</summary>
    public string CategoryTagLabel => _tagFile?.CategoryTag ?? "Category";

    /// <summary>The current tag file's second tag name, used as the search box's label.</summary>
    public string NicknameTagLabel => _tagFile?.NicknameTag ?? "Nickname";

    public bool CanGoToFirstOrPrevious => SelectedCategoryIndex > 0;

    public bool CanGoToNextOrLast => SelectedCategoryIndex >= 0 && SelectedCategoryIndex < DistinctCategories.Count - 1;

    public RelayCommand FirstCategoryCommand { get; }
    public RelayCommand PreviousCategoryCommand { get; }
    public RelayCommand NextCategoryCommand { get; }
    public RelayCommand LastCategoryCommand { get; }

    // ---- 3. Search ----

    public string SearchText
    {
        get => _searchText;
        set
        {
            if (SetProperty(ref _searchText, value))
            {
                ApplyFilter();
            }
        }
    }

    // ---- 4. Records ----

    /// <summary>Records in the selected category matching the current search — the ListView binds to this directly.</summary>
    public ObservableCollection<RecordSummary> Records { get; } = [];

    public RelayCommand AddRecordCommand { get; }

    // ---- Overlay: shared state ----

    public BrowseOverlay Overlay
    {
        get => _overlay;
        private set
        {
            if (SetProperty(ref _overlay, value))
            {
                OnPropertyChanged(nameof(IsDetailOpen));
                OnPropertyChanged(nameof(IsEditingRecord));
                OnPropertyChanged(nameof(IsAddingRecord));
                OnPropertyChanged(nameof(IsEditorOpen));
                OnPropertyChanged(nameof(EditorTitle));
            }
        }
    }

    public bool IsDetailOpen => Overlay == BrowseOverlay.Detail;
    public bool IsEditingRecord => Overlay == BrowseOverlay.EditRecord;
    public bool IsAddingRecord => Overlay == BrowseOverlay.AddRecord;

    /// <summary>True for either Edit or Add — both use the same editable-fields panel, differing only in title and whether Clear shows.</summary>
    public bool IsEditorOpen => IsEditingRecord || IsAddingRecord;

    public string EditorTitle => Overlay switch
    {
        BrowseOverlay.AddRecord => "Add record",
        BrowseOverlay.EditRecord => "Edit record",
        _ => string.Empty,
    };

    // ---- Overlay: read-only Detail (Close / Delete / Edit) ----

    public string SelectedRecordTitle
    {
        get => _selectedRecordTitle;
        private set => SetProperty(ref _selectedRecordTitle, value);
    }

    public IReadOnlyList<TagValue> DetailFields
    {
        get => _detailFields;
        private set => SetProperty(ref _detailFields, value);
    }

    public RelayCommand CloseDetailCommand { get; }
    public RelayCommand DeleteRecordCommand { get; }
    public RelayCommand EditRecordCommand { get; }

    // ---- Overlay: editable Edit/Add (OK [+ Clear]) ----

    /// <summary>Every tag in the current tag file, editable — shared by both Edit and Add.</summary>
    public ObservableCollection<EditableTagValue> EditableFields { get; } = [];

    public string ValidationMessage
    {
        get => _validationMessage;
        private set => SetProperty(ref _validationMessage, value);
    }

    public RelayCommand SaveEditorCommand { get; }
    public RelayCommand ClearAddFormCommand { get; }

    public BrowsePageViewModel()
    {
        FirstCategoryCommand = new RelayCommand(() =>
        {
            if (DistinctCategories.Count > 0)
            {
                SelectedCategoryIndex = 0;
            }
        });
        PreviousCategoryCommand = new RelayCommand(() =>
        {
            if (SelectedCategoryIndex > 0)
            {
                SelectedCategoryIndex--;
            }
        });
        NextCategoryCommand = new RelayCommand(() =>
        {
            if (SelectedCategoryIndex >= 0 && SelectedCategoryIndex < DistinctCategories.Count - 1)
            {
                SelectedCategoryIndex++;
            }
        });
        LastCategoryCommand = new RelayCommand(() =>
        {
            if (DistinctCategories.Count > 0)
            {
                SelectedCategoryIndex = DistinctCategories.Count - 1;
            }
        });

        AddRecordCommand = new RelayCommand(OpenAddRecord);
        CloseDetailCommand = new RelayCommand(CloseOverlay);
        DeleteRecordCommand = new RelayCommand(DeleteRecord);
        EditRecordCommand = new RelayCommand(OpenEditRecord);
        SaveEditorCommand = new RelayCommand(SaveEditor);
        ClearAddFormCommand = new RelayCommand(ClearAddForm);

        ExportCommand = new RelayCommand(async () => await ExportAsync());
        PrintCommand = new RelayCommand(async () => await PrintAsync());

        Refresh();
    }

    /// <summary>
    /// Re-reads which entities exist in AppData and reloads whatever's
    /// selected. Safe to call any time the browse screen becomes visible
    /// again — always reloads even if the selection didn't change, so
    /// records from an Import (or an Add/Edit/Delete elsewhere) show up.
    /// </summary>
    public void Refresh()
    {
        EntityNames = _entityStore.ListEntityNames();

        if (EntityNames.Count == 0)
        {
            _selectedEntityName = null;
            OnPropertyChanged(nameof(SelectedEntityName));
            _tagFile = null;
            _allRecords = [];
            CloseOverlay();
            RecomputeCategories(preferredCategory: null);
            return;
        }

        var entityToLoad = _selectedEntityName is not null && EntityNames.Contains(_selectedEntityName)
            ? _selectedEntityName
            : EntityNames[0];

        if (entityToLoad != _selectedEntityName)
        {
            _selectedEntityName = entityToLoad;
            OnPropertyChanged(nameof(SelectedEntityName));
        }

        LoadEntity(entityToLoad);
    }

    private void LoadEntity(string entityName)
    {
        _tagFile = _entityStore.GetTagFile(entityName);
        _allRecords = _entityStore.GetRecords(entityName).ToList();
        OnPropertyChanged(nameof(CategoryTagLabel));
        OnPropertyChanged(nameof(NicknameTagLabel));
        CloseOverlay();
        RecomputeCategories(preferredCategory: null);
    }

    /// <summary>
    /// Rebuilds the distinct-category list from the current records and
    /// decides which one to land on: <paramref name="preferredCategory"/>
    /// if given and it still exists, else whatever was selected before if
    /// that still exists, else the first one.
    /// </summary>
    private void RecomputeCategories(string? preferredCategory)
    {
        var previous = SelectedCategory;

        var categories = _allRecords
            .Select(r => r.GetValue(_tagFile?.CategoryTag ?? string.Empty) ?? string.Empty)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(c => c, StringComparer.OrdinalIgnoreCase)
            .ToList();

        DistinctCategories = categories;

        var target = preferredCategory ?? previous;
        var index = target is not null
            ? categories.FindIndex(c => string.Equals(c, target, StringComparison.OrdinalIgnoreCase))
            : -1;

        SelectedCategoryIndex = index >= 0 ? index : (categories.Count > 0 ? 0 : -1);

        // SelectedCategoryIndex's own setter only notifies when the index
        // itself changes, but Count (and therefore button enabled-state and
        // the position label) can change even when the index doesn't.
        OnPropertyChanged(nameof(CategoryPositionText));
        OnPropertyChanged(nameof(CanGoToFirstOrPrevious));
        OnPropertyChanged(nameof(CanGoToNextOrLast));
        OnPropertyChanged(nameof(CanExportOrPrint));
        ApplyFilter();
    }

    private void ApplyFilter()
    {
        Records.Clear();

        if (_tagFile is null || SelectedCategory is null)
        {
            return;
        }

        var categoryTag = _tagFile.CategoryTag;
        var nicknameTag = _tagFile.NicknameTag;
        var query = SearchText.Trim();

        foreach (var record in _allRecords)
        {
            var category = record.GetValue(categoryTag) ?? string.Empty;
            if (!string.Equals(category, SelectedCategory, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var nickname = record.GetValue(nicknameTag) ?? string.Empty;
            if (query.Length > 0 && nickname.IndexOf(query, StringComparison.OrdinalIgnoreCase) < 0)
            {
                continue;
            }

            Records.Add(new RecordSummary
            {
                Record = record,
                CategoryValue = category,
                NicknameValue = nickname,
            });
        }
    }

    // ---- Export / Print (README.md §10 — A4, two records per page) ----

    /// <summary>
    /// Writes every record for the current entity (not just the selected
    /// category) to a plain, human-readable .md file — the entity name as
    /// a heading, then "TagName: Value" lines, no internal
    /// <c>:tag.TagName.Value</c> syntax.
    /// </summary>
    private async Task ExportAsync()
    {
        if (_tagFile is null || _allRecords.Count == 0)
        {
            App.Status.SetMessages(["Nothing to export yet."]);
            return;
        }

        var picker = new FileSavePicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, App.WindowHandle);
        picker.SuggestedFileName = $"{_tagFile.EntityName}Print";
        picker.FileTypeChoices.Add("Markdown", [".md"]);
        picker.SuggestedStartLocation = PickerLocationId.DocumentsLibrary;

        var file = await picker.PickSaveFileAsync();
        if (file is null)
        {
            return;
        }

        var content = RecordPrintFormatter.FormatRecords(_tagFile, _allRecords);
        await FileIO.WriteTextAsync(file, content);

        App.Status.SetMessages([$"Exported {_allRecords.Count} record(s) to {file.Name}."]);
    }

    /// <summary>
    /// Builds an A4, two-records-per-page HTML document for every record
    /// in the current entity and opens it in the system default handler
    /// (normally the default browser) so the person can print — or
    /// print-to-PDF — from there. SecretLead doesn't drive a print dialog
    /// itself; see PrintHtmlFormatter for why.
    /// </summary>
    private async Task PrintAsync()
    {
        if (_tagFile is null || _allRecords.Count == 0)
        {
            App.Status.SetMessages(["Nothing to print yet."]);
            return;
        }

        var html = PrintHtmlFormatter.BuildDocument(_tagFile, _allRecords);
        var folder = ApplicationData.Current.TemporaryFolder;
        var file = await folder.CreateFileAsync($"{_tagFile.EntityName}-print.html", CreationCollisionOption.ReplaceExisting);
        await FileIO.WriteTextAsync(file, html);
        await Launcher.LaunchFileAsync(file);

        App.Status.SetMessages([$"Opened {_allRecords.Count} record(s) for printing — use your browser's Print (Ctrl+P)."]);
    }

    // ---- Detail / Edit / Delete ----

    public void OpenDetail(RecordSummary summary)
    {
        if (_tagFile is null)
        {
            return;
        }

        _detailTargetRecord = summary.Record;
        SelectedRecordTitle = summary.NicknameValue.Length > 0 ? summary.NicknameValue : "(no value)";
        DetailFields = _tagFile.Tags
            .Select(tag => new TagValue { TagName = tag, Value = summary.Record.GetValue(tag) ?? string.Empty })
            .ToList();
        Overlay = BrowseOverlay.Detail;
    }

    private void OpenEditRecord()
    {
        if (_tagFile is null || _detailTargetRecord is null)
        {
            return;
        }

        ValidationMessage = string.Empty;
        EditableFields.Clear();
        foreach (var tag in _tagFile.Tags)
        {
            EditableFields.Add(new EditableTagValue { TagName = tag, Value = _detailTargetRecord.GetValue(tag) ?? string.Empty });
        }

        Overlay = BrowseOverlay.EditRecord;
    }

    private void DeleteRecord()
    {
        if (_selectedEntityName is null || _detailTargetRecord is null)
        {
            return;
        }

        _allRecords.Remove(_detailTargetRecord);
        _entityStore.SaveRecords(_selectedEntityName, _allRecords);

        CloseOverlay();
        RecomputeCategories(preferredCategory: null);
    }

    // ---- Add ----

    private void OpenAddRecord()
    {
        if (_tagFile is null)
        {
            return;
        }

        ValidationMessage = string.Empty;
        EditableFields.Clear();
        foreach (var tag in _tagFile.Tags)
        {
            var prefill = tag == _tagFile.CategoryTag ? (SelectedCategory ?? string.Empty) : string.Empty;
            EditableFields.Add(new EditableTagValue { TagName = tag, Value = prefill });
        }

        Overlay = BrowseOverlay.AddRecord;
    }

    private void ClearAddForm()
    {
        foreach (var field in EditableFields)
        {
            field.Value = string.Empty;
        }

        ValidationMessage = string.Empty;
    }

    // ---- Shared save path for Edit/Add ----

    private void SaveEditor()
    {
        if (_tagFile is null || _selectedEntityName is null || !ValidateRequiredFields())
        {
            return;
        }

        if (Overlay == BrowseOverlay.EditRecord && _detailTargetRecord is not null)
        {
            foreach (var field in EditableFields)
            {
                _detailTargetRecord.SetValue(field.TagName, field.Value);
            }

            _entityStore.SaveRecords(_selectedEntityName, _allRecords);

            var updatedCategory = _detailTargetRecord.GetValue(_tagFile.CategoryTag) ?? string.Empty;
            CloseOverlay();
            RecomputeCategories(preferredCategory: updatedCategory);
        }
        else if (Overlay == BrowseOverlay.AddRecord)
        {
            var record = new EntityRecord();
            foreach (var field in EditableFields)
            {
                record.SetValue(field.TagName, field.Value);
            }

            _allRecords.Add(record);
            _entityStore.AppendRecords(_selectedEntityName, [record]);

            var newCategory = record.GetValue(_tagFile.CategoryTag) ?? string.Empty;
            CloseOverlay();
            RecomputeCategories(preferredCategory: newCategory);
        }
    }

    private bool ValidateRequiredFields()
    {
        if (_tagFile is null)
        {
            return false;
        }

        var category = EditableFields.FirstOrDefault(f => f.TagName == _tagFile.CategoryTag);
        var nickname = EditableFields.FirstOrDefault(f => f.TagName == _tagFile.NicknameTag);

        if (string.IsNullOrWhiteSpace(category?.Value) || string.IsNullOrWhiteSpace(nickname?.Value))
        {
            ValidationMessage = $"'{_tagFile.CategoryTag}' and '{_tagFile.NicknameTag}' are required — everything else can stay blank.";
            return false;
        }

        return true;
    }

    /// <summary>
    /// Not a visible button (the owner wants only OK active while editing)
    /// — wired to the Escape key instead, as a safety net that doesn't add
    /// to the button count.
    /// </summary>
    public void CancelEditor() => CloseOverlay();

    private void CloseOverlay()
    {
        Overlay = BrowseOverlay.None;
        _detailTargetRecord = null;
        DetailFields = [];
        ValidationMessage = string.Empty;
    }
}
