// Copyright (c) 2026 edwest19
// Generated by Claude.

using SecretLead.Models;
using SecretLead.Services;
using Windows.Storage;
using Windows.Storage.Pickers;

namespace SecretLead.ViewModels;

/// <summary>
/// Backs the Import screen (README.md §3): two independent file pickers
/// (CSV, tag file), live validation the moment both are selected, and the
/// actual import — tag file copied into AppData, CSV converted and
/// appended — once the Import button is enabled.
/// </summary>
public sealed class ImportPageViewModel : ObservableObject
{
    private readonly EntityStore _entityStore = new();

    private string _csvFileName = "No file selected";
    private string _tagFileName = "No file selected";
    private bool _isReadyToImport;
    private string _resultMessage = string.Empty;

    private CsvTable? _csvTable;
    private TagFileDefinition? _tagFileDefinition;
    private string? _tagFileRawText;

    public string CsvFileName
    {
        get => _csvFileName;
        private set => SetProperty(ref _csvFileName, value);
    }

    public string TagFileName
    {
        get => _tagFileName;
        private set => SetProperty(ref _tagFileName, value);
    }

    /// <summary>
    /// The Import button's own enabled state IS the validation result
    /// (README.md §3) — bound directly in XAML rather than routed through
    /// the command's CanExecute.
    /// </summary>
    public bool IsReadyToImport
    {
        get => _isReadyToImport;
        private set => SetProperty(ref _isReadyToImport, value);
    }

    /// <summary>Inline confirmation shown on this page after a successful import.</summary>
    public string ResultMessage
    {
        get => _resultMessage;
        private set => SetProperty(ref _resultMessage, value);
    }

    public RelayCommand PickCsvFileCommand { get; }
    public RelayCommand PickTagFileCommand { get; }
    public RelayCommand ImportCommand { get; }

    public ImportPageViewModel()
    {
        PickCsvFileCommand = new RelayCommand(async () => await PickCsvFileAsync());
        PickTagFileCommand = new RelayCommand(async () => await PickTagFileAsync());
        ImportCommand = new RelayCommand(Import);
    }

    private async Task PickCsvFileAsync()
    {
        var picker = new FileOpenPicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, App.WindowHandle);
        picker.FileTypeFilter.Add(".csv");
        picker.SuggestedStartLocation = PickerLocationId.Desktop;

        var file = await picker.PickSingleFileAsync();
        if (file is null)
        {
            return;
        }

        ResultMessage = string.Empty;

        try
        {
            var text = await FileIO.ReadTextAsync(file);
            _csvTable = CsvParser.Parse(text);
            CsvFileName = file.Name;
        }
        catch (Exception ex)
        {
            _csvTable = null;
            CsvFileName = "No file selected";
            App.Status.SetMessages([$"CSV file couldn't be read: {ex.Message}"]);
        }

        Revalidate();
    }

    private async Task PickTagFileAsync()
    {
        var picker = new FileOpenPicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, App.WindowHandle);
        picker.FileTypeFilter.Add(".md");
        picker.SuggestedStartLocation = PickerLocationId.Desktop;

        var file = await picker.PickSingleFileAsync();
        if (file is null)
        {
            return;
        }

        ResultMessage = string.Empty;

        try
        {
            var text = await FileIO.ReadTextAsync(file);
            _tagFileDefinition = TagFileParser.Parse(text);
            _tagFileRawText = text;
            TagFileName = file.Name;
        }
        catch (Exception ex)
        {
            _tagFileDefinition = null;
            _tagFileRawText = null;
            TagFileName = "No file selected";
            App.Status.SetMessages([$"Tag file couldn't be read: {ex.Message}"]);
        }

        Revalidate();
    }

    /// <summary>
    /// Runs automatically the moment both files are selected (README.md
    /// §3) — no separate "validate" action. Pushes results to the shared
    /// Status flyout, named explicitly per mismatch (README.md §9).
    /// </summary>
    private void Revalidate()
    {
        if (_csvTable is null || _tagFileDefinition is null)
        {
            IsReadyToImport = false;
            App.Status.SetMessages(["Select both a CSV file and a tag file to validate."]);
            return;
        }

        var result = CsvImporter.Validate(_tagFileDefinition, _csvTable.Headers);
        IsReadyToImport = result.IsValid;

        App.Status.SetMessages(result.IsValid
            ? [$"Every tag matches a CSV column. Ready to import into '{_tagFileDefinition.EntityName}'."]
            : result.Messages);
    }

    private void Import()
    {
        if (_csvTable is null || _tagFileDefinition is null || _tagFileRawText is null || !IsReadyToImport)
        {
            return;
        }

        var entityName = _tagFileDefinition.EntityName;
        var records = CsvImporter.Import(_tagFileDefinition, _csvTable);

        // Tag file is saved before records are written — EntityStore
        // requires it (README.md §3 steps 2 then 3).
        _entityStore.SaveTagFile(entityName, _tagFileRawText);
        _entityStore.AppendRecords(entityName, records);

        ResultMessage = $"Imported {records.Count} record(s) into '{entityName}'.";
        App.Status.SetMessages([ResultMessage]);

        _csvTable = null;
        CsvFileName = "No file selected";
        _tagFileDefinition = null;
        _tagFileRawText = null;
        TagFileName = "No file selected";
        IsReadyToImport = false;
    }
}
