// Copyright (c) 2026 edwest19
// Generated by Claude.

using SecretLead.Services;
using Windows.Storage.Pickers;

namespace SecretLead.ViewModels;

/// <summary>
/// Backs the app shell (<see cref="SecretLead.MainPage"/>): the persistent
/// left nav rail (Import, Backup, Status, Exit) plus the content frame that
/// hosts every other screen (browse/list, Import, etc.).
/// </summary>
public sealed class MainPageViewModel : ObservableObject
{
    // Import navigates ContentFrame directly, so it's a Click handler in
    // MainPage.xaml.cs rather than a command here — no ViewModel-side
    // command needed for it.
    public RelayCommand BackupCommand { get; }
    public RelayCommand ExitCommand { get; }

    /// <summary>Shared status/validation messages shown in the Status flyout (README.md §3).</summary>
    public StatusService Status => App.Status;

    private readonly EntityStore _entityStore = new();

    public MainPageViewModel()
    {
        BackupCommand = new RelayCommand(async () => await BackupAsync());
        ExitCommand = new RelayCommand(Exit);
    }

    /// <summary>
    /// Prompts for a destination folder, then copies every
    /// <c>&lt;EntityName&gt;.txt</c>/<c>.md</c> pair out of AppData into it
    /// (README.md §14) — a safety net against the AppData-wipe scenario
    /// SecretList hit (its <c>records.txt</c> was lost with no recoverable
    /// trace after a Windows feature update). This is the one folder
    /// picker in the app; it's fine because it only ever copies files
    /// *out* of AppData for safekeeping, it never feeds picked files back
    /// in — that's what the Import screen's two file pickers are for (§3).
    /// </summary>
    private async Task BackupAsync()
    {
        if (!Directory.Exists(_entityStore.RootFolder))
        {
            App.Status.SetMessages(["Nothing to back up yet."]);
            return;
        }

        var files = Directory.GetFiles(_entityStore.RootFolder)
            .Where(f => f.EndsWith(".txt", StringComparison.OrdinalIgnoreCase) || f.EndsWith(".md", StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (files.Count == 0)
        {
            App.Status.SetMessages(["Nothing to back up yet."]);
            return;
        }

        var picker = new FolderPicker();
        WinRT.Interop.InitializeWithWindow.Initialize(picker, App.WindowHandle);
        picker.FileTypeFilter.Add("*");
        picker.SuggestedStartLocation = PickerLocationId.Desktop;

        var folder = await picker.PickSingleFolderAsync();
        if (folder is null)
        {
            return;
        }

        foreach (var file in files)
        {
            File.Copy(file, Path.Combine(folder.Path, Path.GetFileName(file)), overwrite: true);
        }

        App.Status.SetMessages([$"Backed up {files.Count} file(s) to {folder.Path}."]);
    }

    private void Exit()
    {
        App.Window.Close();
    }
}
