// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.ViewModels;

/// <summary>
/// Backs the app shell (<see cref="SecretLead.MainPage"/>): the persistent
/// left nav rail (Import, Backup, Status, Exit) plus the content frame that
/// hosts every other screen (browse/list, Import, etc.).
/// </summary>
public sealed class MainPageViewModel : ObservableObject
{
    // Import navigates ContentFrame directly, so it's a Click handler in
    // MainPage.xaml.cs rather than a command here — no ViewModel-side
    // command needed for it.
    public RelayCommand BackupCommand { get; }
    public RelayCommand ExitCommand { get; }

    /// <summary>Shared status/validation messages shown in the Status flyout (README.md §3).</summary>
    public StatusService Status => App.Status;

    public MainPageViewModel()
    {
        BackupCommand = new RelayCommand(Backup);
        ExitCommand = new RelayCommand(Exit);
    }

    private void Backup()
    {
        // TODO: folder picker, then copy every <EntityName>.txt/.md pair out
        // of AppData into the chosen folder. Not built yet.
    }

    private void Exit()
    {
        App.Window.Close();
    }
}
