// Copyright (c) 2026 edwest19
// Generated by Claude.

using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace SecretLead.ViewModels;

/// <summary>
/// Minimal hand-rolled base class for view models. Stands in for
/// CommunityToolkit.Mvvm's ObservableObject, which was removed because it is
/// a third-party NuGet package and README.md §2/§15 forbid those — only the
/// .NET BCL and Windows App SDK / COM are allowed.
/// </summary>
public abstract class ObservableObject : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;

    protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    /// <summary>
    /// Sets the backing field and raises PropertyChanged, but only if the
    /// value actually changed. Returns true when it changed.
    /// </summary>
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value))
        {
            return false;
        }

        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }
}
