// Copyright (c) 2026 edwest19
// Generated by Claude.

using System.Windows.Input;

namespace SecretLead.ViewModels;

/// <summary>
/// Minimal hand-rolled ICommand implementation. Stands in for
/// CommunityToolkit.Mvvm's RelayCommand, which was removed because it is a
/// third-party NuGet package and README.md §2/§15 forbid those.
/// </summary>
public sealed class RelayCommand : ICommand
{
    private readonly Action _execute;
    private readonly Func<bool>? _canExecute;

    public RelayCommand(Action execute, Func<bool>? canExecute = null)
    {
        _execute = execute ?? throw new ArgumentNullException(nameof(execute));
        _canExecute = canExecute;
    }

    public event EventHandler? CanExecuteChanged;

    public bool CanExecute(object? parameter) => _canExecute?.Invoke() ?? true;

    public void Execute(object? parameter) => _execute();

    /// <summary>
    /// There's no source generator here to wire this up automatically —
    /// call this after any state change that might flip CanExecute.
    /// </summary>
    public void RaiseCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty);
}
