// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.ViewModels;

/// <summary>
/// Shared status/validation messages for the shell's status area
/// (README.md §3) — reached via a nav-rail button, not a box permanently
/// visible on any one screen. Any page can push messages here via
/// <c>App.Status</c>; the shell just displays whatever's current.
/// </summary>
public sealed class StatusService : ObservableObject
{
    private IReadOnlyList<string> _messages = ["Nothing to report yet."];

    public IReadOnlyList<string> Messages
    {
        get => _messages;
        private set => SetProperty(ref _messages, value);
    }

    public void SetMessages(IReadOnlyList<string> messages) =>
        Messages = messages.Count > 0 ? messages : ["Nothing to report yet."];
}
