// Copyright (c) 2026 edwest19
// Generated by Claude.

using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Navigation;
using SecretLead.ViewModels;
using Windows.System;

namespace SecretLead;

/// <summary>The browse/list screen — the app's home content (README.md §6, §7).</summary>
public sealed partial class BrowsePage : Page
{
    public BrowsePageViewModel ViewModel { get; } = new();

    public BrowsePage()
    {
        InitializeComponent();
    }

    protected override void OnNavigatedTo(NavigationEventArgs e)
    {
        base.OnNavigatedTo(e);

        // Re-reads AppData every time this page becomes visible, so
        // whatever was just imported (or added/edited/deleted) shows up
        // without a manual refresh.
        ViewModel.Refresh();
    }

    private void RecordsList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (((ListView)sender).SelectedItem is RecordSummary summary)
        {
            ViewModel.OpenDetail(summary);
        }
    }

    // Escape mirrors the Cancel button as a keyboard shortcut for closing
    // the editor without saving.
    private void Page_KeyDown(object sender, KeyRoutedEventArgs e)
    {
        if (e.Key == VirtualKey.Escape && ViewModel.IsEditorOpen)
        {
            ViewModel.CancelEditor();
            e.Handled = true;
        }
    }

    // Small helpers for x:Bind — kept in code-behind since these are
    // view-layer concerns (Visibility, display text), not something the
    // ViewModel should know about.
    public Visibility Visible(bool value) => value ? Visibility.Visible : Visibility.Collapsed;

    public Visibility Collapsed(bool value) => value ? Visibility.Collapsed : Visibility.Visible;

    public string SearchPlaceholder(string nicknameTagLabel) => $"Search {nicknameTagLabel}s…";
}
