// Copyright (c) 2026 edwest19
// Generated by Claude.

using Microsoft.UI.Xaml.Controls;
using SecretLead.ViewModels;

namespace SecretLead;

/// <summary>The Import screen (README.md §3).</summary>
public sealed partial class ImportPage : Page
{
    public ImportPageViewModel ViewModel { get; } = new();

    public ImportPage()
    {
        InitializeComponent();
    }
}
