// Copyright (c) 2026 edwest19
// Generated by Claude.

using SecretLead.Models;

namespace SecretLead.Services;

/// <summary>
/// The one field-normalization rule that is NOT generalized to every tag
/// file (README.md §8): when the bundled Construction demo tag file's
/// "Business Name" is blank, fall back to "Last Name, First Name". Gated on
/// the entity actually being named "Construction" — not just on having
/// those three tag names — so an unrelated user-authored tag file that
/// happens to reuse those tag names isn't silently affected.
/// </summary>
public static class ConstructionFixups
{
    private const string ConstructionEntityName = "Construction";
    private const string BusinessNameTag = "Business Name";
    private const string LastNameTag = "Last Name";
    private const string FirstNameTag = "First Name";

    public static void Apply(TagFileDefinition tagFile, IDictionary<string, string> normalizedValues)
    {
        if (!string.Equals(tagFile.EntityName, ConstructionEntityName, StringComparison.Ordinal))
        {
            return;
        }

        if (!HasTag(tagFile, BusinessNameTag) || !HasTag(tagFile, LastNameTag) || !HasTag(tagFile, FirstNameTag))
        {
            return;
        }

        if (!string.IsNullOrWhiteSpace(normalizedValues[BusinessNameTag]))
        {
            return;
        }

        normalizedValues[BusinessNameTag] = $"{normalizedValues[LastNameTag]}, {normalizedValues[FirstNameTag]}";
    }

    private static bool HasTag(TagFileDefinition tagFile, string tagName) =>
        tagFile.Tags.Any(t => string.Equals(t, tagName, StringComparison.OrdinalIgnoreCase));
}
