// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.Services;

/// <summary>
/// Thrown when CSV text can't be parsed into a table at all — e.g. an
/// empty file or a missing header row. Column/tag mismatches are not this;
/// those are a validation result (README.md §9), not a parse failure.
/// </summary>
public sealed class CsvFormatException : Exception
{
    public CsvFormatException(string message) : base(message)
    {
    }
}
