// Copyright (c) 2026 edwest19
// Generated by Claude.

using SecretLead.Models;

namespace SecretLead.Services;

/// <summary>
/// Converts a validated CSV + tag file into records: normalizes every
/// field (README.md §8), applies the one Construction-specific exception
/// (<see cref="ConstructionFixups"/>), and explodes a semicolon-delimited
/// Category value into one record per value (README.md §4).
/// </summary>
public static class CsvImporter
{
    /// <summary>
    /// Checks a CSV's headers against a tag file's tags, both directions
    /// (README.md §9). Cheap enough to call on every file-selection change
    /// to drive the Import button's gray/green state (README.md §3).
    /// </summary>
    public static ImportValidationResult Validate(TagFileDefinition tagFile, IReadOnlyList<string> csvHeaders)
    {
        var tagSet = new HashSet<string>(tagFile.Tags, StringComparer.OrdinalIgnoreCase);
        var headerSet = new HashSet<string>(csvHeaders, StringComparer.OrdinalIgnoreCase);

        return new ImportValidationResult
        {
            MissingColumns = tagFile.Tags.Where(tag => !headerSet.Contains(tag)).ToList(),
            UnmatchedColumns = csvHeaders.Where(header => !tagSet.Contains(header)).ToList(),
        };
    }

    /// <summary>
    /// Converts every row of a CSV table into one or more records. Callers
    /// should call <see cref="Validate"/> first — this throws if the table
    /// doesn't actually match the tag file, as a safety net rather than a
    /// primary check.
    /// </summary>
    /// <exception cref="InvalidOperationException">The CSV doesn't match the tag file.</exception>
    public static IReadOnlyList<EntityRecord> Import(TagFileDefinition tagFile, CsvTable csvTable)
    {
        var validation = Validate(tagFile, csvTable.Headers);
        if (!validation.IsValid)
        {
            throw new InvalidOperationException(
                "CSV does not match the tag file — call Validate first and only import when IsValid is true. " +
                string.Join(" ", validation.Messages));
        }

        var records = new List<EntityRecord>();

        foreach (var row in csvTable.Rows)
        {
            var normalizedValues = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var tagName in tagFile.Tags)
            {
                var raw = row.TryGetValue(tagName, out var value) ? value : string.Empty;
                normalizedValues[tagName] = FieldNormalizer.Normalize(tagName, raw);
            }

            ConstructionFixups.Apply(tagFile, normalizedValues);

            foreach (var categoryValue in SplitCategory(normalizedValues[tagFile.CategoryTag]))
            {
                var record = new EntityRecord();
                foreach (var tagName in tagFile.Tags)
                {
                    record.SetValue(
                        tagName,
                        tagName == tagFile.CategoryTag ? categoryValue : normalizedValues[tagName]);
                }

                records.Add(record);
            }
        }

        return records;
    }

    /// <summary>
    /// Splits a Category value on ';' into one entry per non-blank piece
    /// (README.md §4) — one input row becomes N output records, all fields
    /// identical except Category. A blank/whitespace Category still yields
    /// exactly one record rather than disappearing.
    /// </summary>
    private static IReadOnlyList<string> SplitCategory(string categoryValue)
    {
        var parts = categoryValue
            .Split(';')
            .Select(p => p.Trim())
            .Where(p => p.Length > 0)
            .ToList();

        return parts.Count > 0 ? parts : [categoryValue];
    }
}
