// Copyright (c) 2026 edwest19
// Generated by Claude.

using System.Text;
using SecretLead.Models;

namespace SecretLead.Services;

/// <summary>
/// Reads and writes the <c>:tag.TagName.Value</c> record format used by
/// every <c>&lt;EntityName&gt;.txt</c> store: one line per field, records
/// separated by a blank line, no separate category/nickname prefix lines
/// (the roles are positional, per the entity's tag file, not encoded in
/// the record text itself).
/// </summary>
/// <remarks>
/// A tag name is assumed to contain no '.' characters (true of every tag
/// used so far — "Business Name", "License ID", etc.). A value may contain
/// '.' freely (URLs, emails) — parsing only looks for the *first* '.' after
/// the tag name to find the value's start, then takes the rest of the line
/// as-is.
/// </remarks>
public static class EntityRecordSerializer
{
    private const string LinePrefix = ":tag.";

    /// <summary>
    /// Parses raw <c>&lt;EntityName&gt;.txt</c> content into records. Lines
    /// that don't match the <c>:tag.</c> format are skipped rather than
    /// treated as errors, so a stray blank line or hand-edited glitch
    /// doesn't take down the whole read.
    /// </summary>
    public static IReadOnlyList<EntityRecord> Parse(string text)
    {
        var records = new List<EntityRecord>();
        var current = new EntityRecord();
        var currentHasFields = false;

        foreach (var rawLine in text.Replace("\r\n", "\n").Split('\n'))
        {
            var line = rawLine.TrimEnd();

            if (line.Length == 0)
            {
                if (currentHasFields)
                {
                    records.Add(current);
                    current = new EntityRecord();
                    currentHasFields = false;
                }

                continue;
            }

            if (!line.StartsWith(LinePrefix, StringComparison.Ordinal))
            {
                continue;
            }

            var afterPrefix = line[LinePrefix.Length..];
            var dotIndex = afterPrefix.IndexOf('.');
            if (dotIndex < 0)
            {
                continue;
            }

            var tagName = afterPrefix[..dotIndex];
            var value = afterPrefix[(dotIndex + 1)..];
            current.SetValue(tagName, value);
            currentHasFields = true;
        }

        if (currentHasFields)
        {
            records.Add(current);
        }

        return records;
    }

    /// <summary>
    /// Serializes records back to <c>:tag.TagName.Value</c> text, one
    /// record per blank-line-separated block, fields written in
    /// <paramref name="tagOrder"/> order (missing values become empty
    /// strings, never omitted lines — keeps every record's line count
    /// consistent with its tag file).
    /// </summary>
    public static string Serialize(IEnumerable<EntityRecord> records, IReadOnlyList<string> tagOrder)
    {
        var sb = new StringBuilder();
        var firstRecord = true;

        foreach (var record in records)
        {
            if (!firstRecord)
            {
                sb.Append('\n');
            }

            firstRecord = false;

            foreach (var tagName in tagOrder)
            {
                var value = record.GetValue(tagName) ?? string.Empty;
                sb.Append(LinePrefix).Append(tagName).Append('.').Append(value).Append('\n');
            }
        }

        return sb.ToString();
    }
}
