// Copyright (c) 2026 edwest19
// Generated by Claude.

using SecretLead.Models;

namespace SecretLead.Services;

/// <summary>
/// Reads and writes the app's sandboxed AppData storage — the only place
/// SecretLead ever writes (README.md §5). Each entity is a pair of files,
/// keyed only by entity name, with no per-source or per-import-session
/// isolation:
/// <list type="bullet">
/// <item><c>&lt;EntityName&gt;.md</c> — the reference copy of the tag file that produced this entity.</item>
/// <item><c>&lt;EntityName&gt;.txt</c> — the actual records.</item>
/// </list>
/// Existence of <c>&lt;EntityName&gt;.txt</c> is the entire discovery
/// mechanism (README.md §6) — there is no separate index or manifest.
/// </summary>
public sealed class EntityStore
{
    private readonly string _rootFolder;

    /// <summary>Uses the app's real sandboxed AppData local folder.</summary>
    public EntityStore()
        : this(Windows.Storage.ApplicationData.Current.LocalFolder.Path)
    {
    }

    /// <summary>Points at an arbitrary folder — for tests or diagnostics only.</summary>
    internal EntityStore(string rootFolder)
    {
        _rootFolder = rootFolder;
    }

    private string TagFilePath(string entityName) => Path.Combine(_rootFolder, $"{entityName}.md");

    private string RecordsFilePath(string entityName) => Path.Combine(_rootFolder, $"{entityName}.txt");

    /// <summary>
    /// True if this entity has ever been imported/seeded — i.e. its
    /// records file exists. This, not any config or index, is the
    /// existence-of-file mechanic from README.md §6.
    /// </summary>
    public bool EntityExists(string entityName) => File.Exists(RecordsFilePath(entityName));

    /// <summary>
    /// Every entity currently in AppData, discovered by the
    /// <c>&lt;EntityName&gt;.txt</c> files present — not by any folder the
    /// owner has open (README.md §6).
    /// </summary>
    public IReadOnlyList<string> ListEntityNames()
    {
        if (!Directory.Exists(_rootFolder))
        {
            return [];
        }

        return Directory.GetFiles(_rootFolder, "*.txt")
            .Select(Path.GetFileNameWithoutExtension)
            .Where(name => !string.IsNullOrEmpty(name))
            .Select(name => name!)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>Reads and parses an entity's stored tag-file copy.</summary>
    /// <exception cref="FileNotFoundException">No tag file is stored for this entity.</exception>
    /// <exception cref="TagFileFormatException">The stored tag file is malformed.</exception>
    public TagFileDefinition GetTagFile(string entityName)
    {
        var path = TagFilePath(entityName);
        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"No stored tag file for entity '{entityName}'.", path);
        }

        return TagFileParser.Parse(File.ReadAllText(path));
    }

    /// <summary>
    /// Writes (or overwrites) an entity's tag-file copy. Called at Import
    /// time (README.md §3 step 2) before records are written, so the store
    /// always has its own self-describing copy independent of wherever the
    /// original tag file came from.
    /// </summary>
    public void SaveTagFile(string entityName, string tagFileMarkdownText)
    {
        Directory.CreateDirectory(_rootFolder);
        File.WriteAllText(TagFilePath(entityName), tagFileMarkdownText);
    }

    /// <summary>
    /// Reads and parses an entity's stored records. Returns an empty list
    /// (not an error) if the entity doesn't exist yet.
    /// </summary>
    public IReadOnlyList<EntityRecord> GetRecords(string entityName)
    {
        var path = RecordsFilePath(entityName);
        if (!File.Exists(path))
        {
            return [];
        }

        return EntityRecordSerializer.Parse(File.ReadAllText(path));
    }

    /// <summary>
    /// Appends records to an entity's store without touching anything
    /// already there — records are never deleted or overwritten by this
    /// call (README.md §3 step 4, §6). Requires the entity's tag file to
    /// already be saved (via <see cref="SaveTagFile"/>), since that's what
    /// supplies field order for the new lines — matching the ordering in
    /// README.md §3, where the tag file is copied in before records are
    /// written.
    /// </summary>
    /// <exception cref="FileNotFoundException">No tag file is stored for this entity yet.</exception>
    public void AppendRecords(string entityName, IEnumerable<EntityRecord> newRecords)
    {
        var recordsList = newRecords as ICollection<EntityRecord> ?? newRecords.ToList();
        if (recordsList.Count == 0)
        {
            return;
        }

        var tagFile = GetTagFile(entityName);
        var newText = EntityRecordSerializer.Serialize(recordsList, tagFile.Tags);

        Directory.CreateDirectory(_rootFolder);
        var path = RecordsFilePath(entityName);

        if (!File.Exists(path))
        {
            File.WriteAllText(path, newText);
            return;
        }

        var existingText = File.ReadAllText(path).TrimEnd('\n', '\r');
        File.WriteAllText(path, existingText + "\n\n" + newText);
    }

    /// <summary>
    /// Overwrites an entity's entire record store. Used by manual
    /// edit/delete flows (README.md §7) — Import never calls this, it only
    /// ever appends.
    /// </summary>
    /// <exception cref="FileNotFoundException">No tag file is stored for this entity yet.</exception>
    public void SaveRecords(string entityName, IEnumerable<EntityRecord> records)
    {
        var tagFile = GetTagFile(entityName);
        Directory.CreateDirectory(_rootFolder);
        File.WriteAllText(RecordsFilePath(entityName), EntityRecordSerializer.Serialize(records, tagFile.Tags));
    }
}
