// Copyright (c) 2026 edwest19
// Generated by Claude.

using System.Net;
using System.Text;
using SecretLead.Models;

namespace SecretLead.Services;

/// <summary>
/// Builds a print-ready HTML document, two records per A4 page. This
/// exists instead of driving WinUI's native print APIs directly: WinUI 3
/// desktop apps don't have UWP's old <c>PrintDocument</c> print helper, and
/// hand-rolling the low-level replacement is a large, fragile undertaking
/// for what "two records per page" actually needs — real page-break
/// control. A browser's print pipeline already does that correctly via
/// CSS, so the Print button opens this file and lets the person print (or
/// print-to-PDF) from there, rather than SecretLead trying to drive a
/// print dialog itself.
/// </summary>
public static class PrintHtmlFormatter
{
    public static string BuildDocument(TagFileDefinition tagFile, IReadOnlyList<EntityRecord> records)
    {
        var sb = new StringBuilder();
        sb.Append("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n");
        sb.Append("<title>").Append(WebUtility.HtmlEncode(tagFile.EntityName)).Append("</title>\n");
        sb.Append("""
            <style>
                @page { size: A4; margin: 1.5cm; }
                body { font-family: 'Segoe UI', sans-serif; color: #1a1a1a; margin: 0; }
                .sheet { page-break-after: always; display: flex; flex-direction: column; gap: 1cm; min-height: 25cm; }
                .sheet:last-child { page-break-after: auto; }
                .record { border: 1px solid #999; border-radius: 4px; padding: 0.6cm; flex: 1; }
                .record h2 { margin: 0 0 0.3cm 0; font-size: 14pt; }
                .field { display: flex; gap: 0.3cm; margin: 0.15cm 0; font-size: 10pt; }
                .field .label { font-weight: 600; min-width: 3.2cm; color: #555; }
            </style>
            """);
        sb.Append("\n</head>\n<body>\n");

        for (var i = 0; i < records.Count; i += 2)
        {
            sb.Append("<div class=\"sheet\">\n");
            sb.Append(RenderRecord(tagFile, records[i]));
            if (i + 1 < records.Count)
            {
                sb.Append(RenderRecord(tagFile, records[i + 1]));
            }

            sb.Append("</div>\n");
        }

        sb.Append("</body>\n</html>\n");
        return sb.ToString();
    }

    private static string RenderRecord(TagFileDefinition tagFile, EntityRecord record)
    {
        var sb = new StringBuilder();
        sb.Append("<div class=\"record\">\n");
        sb.Append("<h2>").Append(WebUtility.HtmlEncode(tagFile.EntityName)).Append("</h2>\n");

        foreach (var tag in tagFile.Tags)
        {
            var value = record.GetValue(tag) ?? string.Empty;
            sb.Append("<div class=\"field\"><span class=\"label\">")
                .Append(WebUtility.HtmlEncode(tag))
                .Append("</span><span class=\"value\">")
                .Append(WebUtility.HtmlEncode(value))
                .Append("</span></div>\n");
        }

        sb.Append("</div>\n");
        return sb.ToString();
    }
}
