// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.Services;

/// <summary>
/// Thrown when a tag file's Markdown doesn't follow the grammar in
/// README.md §4 — for example no <c>##</c> entity-name line, more than one
/// of them, or fewer than the 2 tags required for the Category/Nickname
/// roles.
/// </summary>
public sealed class TagFileFormatException : Exception
{
    public TagFileFormatException(string message) : base(message)
    {
    }
}
