# Copyright (c) 2026 edwest19
# Generated by Claude.

<#
.SYNOPSIS
    Resets SecretLead to first-run state.

.DESCRIPTION
    Deletes every stored entity (<EntityName>.md / <EntityName>.txt) from
    SecretLead's AppData folder. Existence-of-file is the whole mechanism
    SecretLead uses to know what entities exist (README.md §6), so removing
    these files is a complete, clean reset -- there's no other index, cache,
    or database tracking anything.

    SecretLead is distributed as an unpackaged, self-contained app (no
    MSIX, no package identity), so its AppData folder is a plain
    %LOCALAPPDATA%\SecretLead folder, resolved via
    Environment.SpecialFolder.LocalApplicationData -- not a packaged
    %LOCALAPPDATA%\Packages\<PackageFamilyName>\LocalState folder. This
    matches EntityStore's parameterless constructor exactly
    (Services/EntityStore.cs).

.PARAMETER Force
    Skip the confirmation prompt.

.EXAMPLE
    .\scripts\Reset-SecretLeadAppData.ps1

.EXAMPLE
    .\scripts\Reset-SecretLeadAppData.ps1 -Force

.NOTES
    If Windows blocks this script ("running scripts is disabled on this
    system"), either right-click the file > Properties > Unblock, or run:
        powershell -ExecutionPolicy Bypass -File .\scripts\Reset-SecretLeadAppData.ps1
#>
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [switch]$Force
)

$localState = Join-Path $env:LOCALAPPDATA "SecretLead"

if (-not (Test-Path $localState)) {
    Write-Host "No AppData folder found at $localState -- nothing to reset."
    exit 0
}

$files = @(Get-ChildItem -Path $localState -Filter '*.md' -File) + @(Get-ChildItem -Path $localState -Filter '*.txt' -File)

if ($files.Count -eq 0) {
    Write-Host "AppData is already empty -- nothing to reset."
    exit 0
}

Write-Host "Found $($files.Count) file(s) in $localState :"
$files | ForEach-Object { Write-Host "  $($_.Name)" }

if ($Force -or $PSCmdlet.ShouldProcess($localState, "Delete $($files.Count) file(s)")) {
    $files | Remove-Item -Force
    Write-Host "Done. SecretLead will seed fresh on next launch."
}
