// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.Models;

/// <summary>
/// A parsed CSV file: the header row, plus each data row as a
/// case-insensitive column-name → value lookup (matching how tag names are
/// matched against CSV headers everywhere else — README.md §4).
/// </summary>
public sealed class CsvTable
{
    public required IReadOnlyList<string> Headers { get; init; }

    public required IReadOnlyList<IReadOnlyDictionary<string, string>> Rows { get; init; }
}
