// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.Models;

/// <summary>
/// One record belonging to some entity (e.g. one Construction row). Holds
/// tag-name/value pairs with no fixed shape of its own — the shape comes
/// from whichever <see cref="TagFileDefinition"/> produced it.
/// </summary>
/// <remarks>
/// Tag names are matched case-insensitively everywhere else in the spec
/// (README.md §4, §8), so lookups here are case-insensitive too.
/// </remarks>
public sealed class EntityRecord
{
    private readonly Dictionary<string, string> _fields = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Read-only view of every tag/value pair currently set.</summary>
    public IReadOnlyDictionary<string, string> Fields => _fields;

    /// <summary>
    /// Returns the value for <paramref name="tagName"/>, or null if this
    /// record has nothing stored for that tag.
    /// </summary>
    public string? GetValue(string tagName) =>
        _fields.TryGetValue(tagName, out var value) ? value : null;

    /// <summary>Sets (or overwrites) the value for a tag.</summary>
    public void SetValue(string tagName, string value) => _fields[tagName] = value;
}
