// Copyright (c) 2026 edwest19
// Generated by Claude.

namespace SecretLead.Models;

/// <summary>
/// Result of checking a CSV's headers against a tag file's tags
/// (README.md §9) — a hard stop in both directions, with every mismatch
/// named explicitly rather than summarized.
/// </summary>
public sealed class ImportValidationResult
{
    /// <summary>Tags with no matching CSV column.</summary>
    public required IReadOnlyList<string> MissingColumns { get; init; }

    /// <summary>CSV columns with no matching tag.</summary>
    public required IReadOnlyList<string> UnmatchedColumns { get; init; }

    public bool IsValid => MissingColumns.Count == 0 && UnmatchedColumns.Count == 0;

    /// <summary>
    /// One human-readable line per mismatch, meant to be shown verbatim in
    /// the status area (README.md §3) — never collapsed into a summary.
    /// </summary>
    public IReadOnlyList<string> Messages
    {
        get
        {
            var messages = new List<string>();

            foreach (var tag in MissingColumns)
            {
                messages.Add($"Tag '{tag}' has no matching CSV column.");
            }

            foreach (var column in UnmatchedColumns)
            {
                messages.Add($"CSV column '{column}' has no matching tag.");
            }

            return messages;
        }
    }
}
